#pragma once

#include <stdint.h>

// Trap Codes
#define INT 0
#define TRAP_IBUS 1
#define TRAP_ADDRESS_LOAD_ERROR 4
#define TRAP_ADDRESS_STORE_ERROR 5
#define TRAP_SYSCALL 8
#define TRAP_BREAKPOINT 9
#define TRAP_RESERVED_INSTRUCTION 10
#define TRAP_OVERFLOW 12

#define SYSCALL_PRINT_INT 1
#define SYSCALL_PRINT_FLOAT 2
#define SYSCALL_PRINT_DOUBLE 3
#define SYSCALL_PRINT_STRING 4
#define SYSCALL_READ_INT 5
#define SYSCALL_READ_FLOAT 6
#define SYSCALL_READ_DOUBLE 7
#define SYSCALL_READ_STRING 8
#define SYSCALL_SBRK 9
#define SYSCALL_EXIT 10
#define SYSCALL_PRINT_CHARACTER 11
#define SYSCALL_READ_CHARACTER 12
#define SYSCALL_OPEN_FILE 13
#define SYSCALL_READ_FILE 14
#define SYSCALL_WRITE_FILE 15
#define SYSCALL_CLOSE_FILE 16
#define SYSCALL_EXIT2 17

void handle_syscall();

