from typing import Final, Callable

from tools.assembler.instruction import Instruction

from tools.assembler.parsers import (
    parse_rd_rs_rt,
    parse_rd_rt_shamt,
    parse_rs,
    parse_rd,
    parse_rs_rt,
    parse_rt_rs_imm,
    parse_rt_imm,
    parse_rt_offset_rs,
    parse_label,
    parse_rs_rt_label,
    parse_rd_rs,
    parse_rs_label,
    parse_jalr
)

OPCODES : Final[dict[str, int]] = {
    'sll':   0x00,
    'srl':   0x00,
    'sra':   0x00,
    'jr':    0x00,
    'jalr':  0x00,
    'mfhi':  0x00,
    'mthi':  0x00,
    'mflo':  0x00,
    'mtlo':  0x00,
    'mult':  0x00,
    'multu': 0x00,
    'div':   0x00,
    'divu':  0x00,
    'add':   0x00,
    'addu':  0x00,
    'sub':   0x00,
    'subu':  0x00,
    'and':   0x00,
    'or':    0x00,
    'xor':   0x00,
    'nor':   0x00,
    'slt':   0x00,
    'sltu':  0x00,
    'beq':   0x04,
    'bne':   0x05,
    'blez':  0x06,
    'bgtz':  0x07,
    'addi':  0x08,
    'addiu': 0x09,
    'slti':  0x0A,
    'sltiu': 0x0B,
    'andi':  0x0C,
    'ori':   0x0D,
    'lui':   0x0F,
    'lb':    0x20, 
    'lh':    0x21, 
    'lw':    0x23, 
    'lbu':   0x24,
    'lhu':   0x25,
    'sb':    0x28,
    'sh':    0x29,
    'sw':    0x2B,
    'j':     0x02,
    'jal':   0x03,
}

FUNCTS : Final[dict[str, int]] = {
    'sll':   0x00,
    'srl':   0x02,
    'sra':   0x03,
    'jr':    0x08,
    'jalr':  0x09,
    'mfhi':  0x10,
    'mthi':  0x11,
    'mflo':  0x12,
    'mtlo':  0x13,
    'mult':  0x18,
    'multu': 0x19,
    'div':   0x1A,
    'divu':  0x1B,
    'add':   0x20,
    'addu':  0x21,
    'sub':   0x22,
    'subu':  0x23,
    'and':   0x24,
    'or':    0x25,
    'xor':   0x26,
    'nor':   0x27,
    'slt':   0x2A,
    'sltu':  0x2B,
}

INSTRUCTION_PARSERS: Final[dict[str, Callable[[str], Instruction]]] = {
    'sll':   parse_rd_rt_shamt,
    'srl':   parse_rd_rt_shamt,
    'sra':   parse_rd_rt_shamt,
    'jr':    parse_rs,
    'jalr':  parse_jalr,
    'mfhi':  parse_rd,
    'mthi':  parse_rs,
    'mflo':  parse_rd,
    'mtlo':  parse_rs,
    'mult':  parse_rs_rt,
    'multu': parse_rs_rt,
    'div':   parse_rs_rt,
    'divu':  parse_rs_rt,
    'add':   parse_rd_rs_rt,
    'addu':  parse_rd_rs_rt,
    'sub':   parse_rd_rs_rt,
    'subu':  parse_rd_rs_rt,
    'and':   parse_rd_rs_rt,
    'or':    parse_rd_rs_rt,
    'xor':   parse_rd_rs_rt,
    'nor':   parse_rd_rs_rt,
    'slt':   parse_rd_rs_rt,
    'sltu':  parse_rd_rs_rt,
    'beq':   parse_rs_rt_label,
    'bne':   parse_rs_rt_label,
    'blez':  parse_rs_label,
    'bgtz':  parse_rs_label,
    'addi':  parse_rt_rs_imm,
    'addiu': parse_rt_rs_imm,
    'slti':  parse_rt_rs_imm,
    'sltiu': parse_rt_rs_imm,
    'andi':  parse_rt_rs_imm,
    'ori':   parse_rt_rs_imm,
    'lui':   parse_rt_imm,
    'lb':    parse_rt_offset_rs, 
    'lh':    parse_rt_offset_rs, 
    'lw':    parse_rt_offset_rs, 
    'lbu':   parse_rt_offset_rs,
    'lhu':   parse_rt_offset_rs,
    'sb':    parse_rt_offset_rs,
    'sh':    parse_rt_offset_rs,
    'sw':    parse_rt_offset_rs,
    'j':     parse_label,
    'jal':   parse_label,
}
